{% set name = "pyre2" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2234533c16bfd49234fe9f7ca694ccc7b7e26e5642cac3fd7874ac73f144668b
  patches:
    - setup-py.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
    - re2
  run:
    - python
    - re2

test:
  imports:
    - re2
  source_files:
    - tests
  commands:
    - python -m unittest discover -f -s tests

about:
  home: "https://pypi.org/project/pyre2/"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Python wrapper for Google's RE2 using Cython"
  doc_url: "https://github.com/andreasvc/pyre2/blob/master/README.rst"
  dev_url: "https://github.com/andreasvc/pyre2"

extra:
  recipe-maintainers:
    - sarnold
